name: GraphscoreDTA
channels:
- pytorch
- pypi
- dglteam
- defaults
dependencies:
- python=3.7.11
- pytorch=1.9.0
- scikit-learn=0.24.2
- dgl-cuda10.2
- tqdm=4.62.2
- ipython=7.27.0
- numpy=1.20.3
- pandas=1.3.2
- numba=0.53.1
- scipy=1.7.1